version: '3.8'
services:
  primes-service:
    container_name: primes-service
    build:
      context: ..
      dockerfile: Dockerfile
    image: prime-service
    ports:
      - "4001:8080"
    restart: "no"