spring:
  application:
    name: prime-service
  datasource:
    url: jdbc:postgresql://primes-database:5432/primes
    username: postgres
    password: password
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    edu.iu.p466.prime_service: DEBUG
    org.springframework.web: DEBUG