name: Test, Create Image, Push to Github Container Registry
on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests
        run: mvn test -f prime-service/pom.xml

      - name: Build Package
        run: mvn package -f prime-service/pom.xml

      - name: Build and Push Docker Image
        run: |
          docker login --username jentezar --password ${{ secrets.ACCESS_TOKEN }} ghcr.io
          docker build -t ghcr.io/jentezar/primes-service:latest --file Dockerfile .
          docker push ghcr.io/jentezar/primes-service:latest
