name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: practicumsp466.azurecr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Build and publish to GHCR
        run: |
          docker login --username jentezar --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/jentezar/arithmetic-service:$VERSION --file Dockerfile .
          docker tag ghcr.io/jentezar/arithmetic-service:$VERSION ghcr.io/jentezar/arithmetic-service:latest
          docker push ghcr.io/jentezar/arithmetic-service:$VERSION
          docker push ghcr.io/jentezar/arithmetic-service:latest

      - name: Publish to Azure Container Registry
        run: |
          docker login --username ${{ secrets.AZURE_CONTAINER_REGISTRY_UN }} --password ${{ secrets.AZURE_CONTAINER_REGISTRY_PW }} practicumsp466.azurecr.io
          docker tag ghcr.io/jentezar/arithmetic-service:$VERSION practicumsp466.azurecr.io/arithmetic-service:$VERSION
          docker push practicumsp466.azurecr.io/arithmetic-service:$VERSION

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      
      # Create image pull secret before deploying
      - name: Create Image Pull Secret
        run: |
          kubectl create secret docker-registry acr-secret \
            --docker-server=$CONTAINER_REGISTRY \
            --docker-username=${{ secrets.AZURE_CONTAINER_REGISTRY_UN }} \
            --docker-password=${{ secrets.AZURE_CONTAINER_REGISTRY_PW }} \
            --dry-run=client -o yaml | kubectl apply -f -
      
      - name: Deploy
        run: ./deploy.sh