name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      CONTAINER_REGISTRY_UN: ${{ secrets.CONTAINER_REGISTRY_UN }}
      CONTAINER_REGISTRY_PW: ${{ secrets.CONTAINER_REGISTRY_PW }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Build and push to GitHub Container Registry
        run: |
          docker login --username jentezar --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/jentezar/arithmetic-service:$VERSION --file Dockerfile .
          docker push ghcr.io/jentezar/arithmetic-service:$VERSION

      - name: Publish to Azure Container Registry
        run: |
          docker login practicumsp466.azurecr.io --username practicumsp466 --password ${{ secrets.AZURE_CONTAINER_REGISTRY_PW }}
          docker tag ghcr.io/jentezar/arithmetic-service:$VERSION practicumsp466.azurecr.io/arithmetic-service:$VERSION
          docker push practicumsp466.azurecr.io/arithmetic-service:$VERSION

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBECONFIG_FILE" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          chmod +x ./deploy.sh
          ./deploy.sh